# -*- coding: utf-8 -*-
"""Data Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Keogy5mYI-_ukCshcaHT0W1Wog7psrVu
"""

import pandas as pd
import numpy as np

np.random.seed(42)

n_samples = 1000

time = pd.date_range(start="2025-01-01", periods=n_samples, freq="h")

# Simulate multiple locations (e.g., tourist bridges)
locations = [
    {"name": "Bridge_A", "lat": 13.0827, "lon": 80.2707, "elev": 6},   # Chennai
    {"name": "Bridge_B", "lat": 12.9716, "lon": 77.5946, "elev": 920}, # Bangalore
    {"name": "Bridge_C", "lat": 11.0168, "lon": 76.9558, "elev": 411}, # Coimbatore
]

# Randomly assign locations
loc_choices = np.random.choice(len(locations), n_samples)

latitude = [locations[i]["lat"] + np.random.normal(0, 0.001) for i in loc_choices]
longitude = [locations[i]["lon"] + np.random.normal(0, 0.001) for i in loc_choices]
elevation = np.array([locations[i]["elev"] + np.random.normal(0, 5) for i in loc_choices]) # Convert elevation to numpy array
location_name = [locations[i]["name"] for i in loc_choices]

# Sensor data
crowd_load = np.random.randint(0, 500, n_samples)
temperature = np.random.uniform(15, 45, n_samples)

# Pressure slightly depends on elevation (higher → lower pressure)
pressure = 1013 - (elevation * 0.12) + np.random.normal(0, 5, n_samples) # elevation is now a numpy array

vibration = np.random.uniform(0, 5, n_samples)

# Stress formula (include elevation effect)
stress = (
    0.5 * crowd_load +
    0.3 * temperature +
    0.2 * pressure +
    10 * vibration +
    0.1 * elevation + # This will now work correctly as elevation is a numpy array
    np.random.normal(0, 20, n_samples)
)

# Labels
conditions = [
    stress < 300,
    (stress >= 300) & (stress < 600),
    stress >= 600
]
labels = ["Safe", "Warning", "Danger"]

status = np.select(conditions, labels, default="Undefined") # Added default string value

# DataFrame
df = pd.DataFrame({
    "timestamp": time,
    "location": location_name,
    "latitude": latitude,
    "longitude": longitude,
    "elevation": elevation,
    "crowd_load": crowd_load,
    "temperature": temperature,
    "pressure": pressure,
    "vibration": vibration,
    "stress": stress,
    "status": status
})

df.to_csv("synthetic_stress_data.csv", index=False)
from google.colab import files
files.download("synthetic_stress_data.csv")