services:
  - type: web
    name: stressnet-cloud-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements_dashboard.txt
    startCommand: streamlit run cloud_live_dashboard.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: USE_SIMULATION
        value: "true"
      - key: SIMULATION_CSV
        value: thingspeak_demo.csv
      - key: MODEL_PATH
        value: stress_model.pkl
      - key: REFERENCE_DATA
        value: synthetic_stress_data_3class.csv
